name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-ws:1.0

      - name: Deploy to server
        run: |
          echo "Starting deployment..."
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "SSH connection established."
            docker pull ${{ secrets.DOCKER_USERNAME }}/todo-ws:1.0
            echo "Docker pull successful."
            docker stop todo-ws || true
            echo "Docker container stopped."
            docker rm todo-ws || true
            echo "Docker container removed."
            docker-compose -f docker-compose.yml up -d
#            docker run -d --name todo-ws -p 8083:8082 ${{ secrets.DOCKER_USERNAME }}/todo-ws:1.0
            echo "Docker container deployed successfully."
          EOF